#define MEME_DIR "/Users/sjmcilwain"
#define DATA_DIR "/Users/sjmcilwain/share/meme-5.5.6" 
#define BIN_DIR "/Users/sjmcilwain/bin" 
#define LIBEXEC_DIR "/Users/sjmcilwain/libexec/meme-5.5.6" 
#define TEMP_DIR "" 
